name: coolweather
description: A new Flutter application about weather forecast.

version: 1.3.0+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: '>=0.11.3+12'
  quiver: '>=2.0.0 <3.0.0'
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.3+4
  amap_location:
  fluttertoast: ^3.1.3
  permission_handler: ^3.2.0
  provider: ^3.1.0
  package_info: ^0.4.0+6
  esys_flutter_share: ^1.0.2
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/bg_main.png
    - images/ic_location.png
    - images/ic_building.png
    - images/ic_launcher.png
    - images/ic_weather/ic_cloud.png
    - images/ic_weather/ic_haze.png
    - images/ic_weather/ic_nosun.png
    - images/ic_weather/ic_rain.png
    - images/ic_weather/ic_snow.png
    - images/ic_weather/ic_sunny.png
    - images/ic_weather/ic_sunny_night.png
    - images/ic_weather/ic_wind.png
    - images/ic_weather/ic_sunrise.png
    - images/ic_weather/ic_sunset.png
    - images/bg_weather/bg_sunny.png
    - images/bg_weather/bg_sunny_night.png
    - images/bg_weather/bg_cloudy.png
    - images/bg_weather/bg_cloudy_night.png
    - images/bg_weather/bg_overcast.png
    - images/bg_weather/bg_overcast_night.png
    - images/bg_weather/bg_sunny.png
    - images/bg_weather/bg_sunny_night.png
    - images/bg_weather/bg_haze.png
    - images/bg_weather/bg_haze_night.png
    - images/bg_weather/bg_downpour.png
    - images/bg_weather/bg_downpour_night.png
    - images/bg_weather/bg_snow.png
    - images/bg_weather/bg_snow_night.png
    - images/bg_weather/bg_drizzle.png
    - images/bg_weather/bg_drizzle_night.png
    - images/bg_share/bg_sunny_share.png
    - images/bg_share/bg_sunny_night_share.png
    - images/bg_share/bg_cloudy_share.png
    - images/bg_share/bg_cloudy_night_share.png
    - images/bg_share/bg_overcast_share.png
    - images/bg_share/bg_overcast_night_share.png
    - images/bg_share/bg_sunny_share.png
    - images/bg_share/bg_sunny_night_share.png
    - images/bg_share/bg_haze_share.png
    - images/bg_share/bg_haze_night_share.png
    - images/bg_share/bg_drizzle_share.png
    - images/bg_share/bg_drizzle_night_share.png
    - images/bg_share/bg_rain_share.png
    - images/bg_share/bg_rain_night_share.png
    - images/bg_share/bg_downpour_share.png
    - images/bg_share/bg_downpour_night_share.png
    - images/bg_share/bg_rainstorm_share.png
    - images/bg_share/bg_rainstorm_night_share.png
    - images/bg_share/bg_downpour_share.png
    - images/bg_share/bg_snow_share.png
    - images/bg_share/bg_snow_night_share.png